"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { ensureMonth } from "@/lib/data";
export async function createExpense(formData: FormData) { const supabase = await createClient(); const amount = Number(formData.get("amount")); const category_id = String(formData.get("category_id")); const expense_date = String(formData.get("expense_date")); const note = String(formData.get("note") ?? "").trim(); if (!amount || amount <= 0 || !category_id || !expense_date) throw new Error("Enter an amount, category, and date."); const { error } = await supabase.from("expenses").insert({ amount, category_id, expense_date, note: note || null, capture_method: "manual" }); if (error) throw new Error(error.message); revalidatePath("/"); revalidatePath("/expenses"); }
export async function deleteExpense(id: string) { const supabase = await createClient(); const { error } = await supabase.from("expenses").delete().eq("id", id); if (error) throw new Error(error.message); revalidatePath("/"); revalidatePath("/expenses"); }
export async function updateBudget(formData: FormData) { const supabase = await createClient(); const month = String(formData.get("month")); const category_id = String(formData.get("category_id")); const amount = Number(formData.get("allocated_amount")); const { error } = await supabase.from("budgets").update({ allocated_amount: amount }).eq("month", month).eq("category_id", category_id); if (error) throw new Error(error.message); revalidatePath("/"); revalidatePath("/budget"); }
export async function generateRecommendation() { const supabase = await createClient(); const month = new Date().toISOString().slice(0, 7); await ensureMonth(month); const { data: rows } = await supabase.from("expenses").select("amount,category_id,categories(name,type)").gte("expense_date", `${month}-01`).lt("expense_date", `${month}-32`); if (!rows || rows.length < 5) throw new Error("Need at least 5 expenses this month to generate recommendations."); const totals = rows.filter((r) => (r.categories as any)?.type !== "fixed").reduce((acc: Record<string, number>, r) => { acc[r.category_id] = (acc[r.category_id] ?? 0) + Number(r.amount); return acc; }, {}); const topId = Object.entries(totals).sort((a, b) => b[1] - a[1])[0]?.[0]; const top = rows.find((r) => r.category_id === topId)?.categories as any; if (!topId || !top) throw new Error("Not enough variable expenses to recommend yet."); const suggestion = `${top.name} is your largest flexible spend at MYR ${totals[topId].toFixed(2)}. Try a small, repeatable reduction before making bigger lifestyle changes.`; const { error } = await supabase.from("recommendations").insert({ month, top_reducible_category_id: topId, suggestion_text: suggestion, primary_idea: `Reduce ${top.name} by one purchase or visit per week.`, backup_idea: "Set a weekly cash cap and review it every Sunday.", risks_text: "Avoid cutting essentials or social time too aggressively; adjust after two weeks.", next_actions: ["Review the last seven days of spending", "Set a weekly limit for this category", "Check progress next Sunday"], source: process.env.OPENAI_API_KEY ? "openai-gpt" : "rule-based", confidence: 0.8, review_status: "unreviewed" }); if (error) throw new Error(error.message); revalidatePath("/"); revalidatePath("/recommendations"); }
export async function updateRecommendation(id: string, status: "accepted" | "dismissed") { const supabase = await createClient(); const { error } = await supabase.from("recommendations").update({ review_status: status }).eq("id", id); if (error) throw new Error(error.message); revalidatePath("/"); revalidatePath("/recommendations"); }
